const CURRENT=2026;
const TEAM_SLUGS={ARI:'arizona-cardinals',ATL:'atlanta-falcons',BAL:'baltimore-ravens',BUF:'buffalo-bills',CAR:'carolina-panthers',CHI:'chicago-bears',CIN:'cincinnati-bengals',CLE:'cleveland-browns',DAL:'dallas-cowboys',DEN:'denver-broncos',DET:'detroit-lions',GB:'green-bay-packers',HOU:'houston-texans',IND:'indianapolis-colts',JAX:'jacksonville-jaguars',KC:'kansas-city-chiefs',LV:'las-vegas-raiders',LAC:'los-angeles-chargers',LAR:'los-angeles-rams',MIA:'miami-dolphins',MIN:'minnesota-vikings',NE:'new-england-patriots',NO:'new-orleans-saints',NYG:'new-york-giants',NYJ:'new-york-jets',PHI:'philadelphia-eagles',PIT:'pittsburgh-steelers',SF:'san-francisco-49ers',SEA:'seattle-seahawks',TB:'tampa-bay-buccaneers',TEN:'tennessee-titans',WAS:'washington-commanders'};
const ALIASES={JAC:'JAX',WSH:'WAS',LA:'LAR'};
function clean(s=''){return String(s).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&#39;|&apos;/gi,"'").replace(/&quot;/gi,'"').replace(/\s+/g,' ').trim()}
function cells(row){const a=[];let m;const re=/<t[dh]\b[^>]*>([\s\S]*?)<\/t[dh]>/gi;while((m=re.exec(row)))a.push(clean(m[1]));return a}
function cash(v=''){const s=String(v).replace(/,/g,'');const m=s.match(/\$?\s*(-?[0-9]+(?:\.[0-9]+)?)\s*(B|M|K|billion|million|thousand)?/i);if(!m)return 0;const u=String(m[2]||'').toLowerCase(),mult=/^b|billion/.test(u)?1e9:/^m|million/.test(u)?1e6:/^k|thousand/.test(u)?1e3:1;return Math.round(Number(m[1])*mult)}
function team(v=''){const m=String(v).toUpperCase().match(/\b([A-Z]{2,3})\b/);const a=m?.[1]||'';return ALIASES[a]||a}
async function fetchText(url,ms=18000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,cache:'no-store',headers:{'user-agent':'Mozilla/5.0 CapLab/1.0','accept':'text/html,application/xhtml+xml','cache-control':'no-cache'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text()}finally{clearTimeout(t)}}
function rows(html){const out=[];let m;const re=/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi;while((m=re.exec(html))){const c=cells(m[1]);if(c.length)out.push(c)}return out}
export function parseCapHistory(html,year){const out=[];for(const c of rows(html)){const abbr=team(c[1]||c[0]);if(!TEAM_SLUGS[abbr])continue;const money=c.filter(x=>/\$/.test(x)).map(cash);if(money.length<3)continue;let total=0,space=0,active=0,dead=0;if(year>=2026){total=money[1]||money[0];space=money[2]||0;active=money[money.length-2]||0;dead=money[money.length-1]||0;}else{total=money[0]||0;space=money[1]||0;active=money[money.length-2]||0;dead=money[money.length-1]||0;}out.push({team:abbr,year,totalAllocations:total,capSpace:space,activeSpend:active,deadMoney:dead,source:'Spotrac'});}return [...new Map(out.map(x=>[x.team,x])).values()]}
export function parsePositionHistory(html,year){const out=[];for(const c of rows(html)){const abbr=team(c[0]);if(!TEAM_SLUGS[abbr])continue;const labels=['QB','RB','WR','TE','OL','EDGE','DL','LB','CB','S','K','P','LS'];const vals=c.slice(1).filter(x=>/\$/.test(x)).map(cash);if(vals.length<8)continue;const positions={};labels.forEach((k,i)=>positions[k]=vals[i]||0);out.push({team:abbr,year,positions,total:vals[13]||vals.reduce((a,b)=>a+b,0),source:'Spotrac'});}return [...new Map(out.map(x=>[x.team,x])).values()]}
export function parseDraft(html,year){const out=[];for(const c of rows(html)){const round=Number(c[0]),pick=Number(c[1]);if(!round||!pick)continue;const abbr=team(c[2]);if(!TEAM_SLUGS[abbr])continue;const name=(c[4]||c[3]||'').trim(),pos=(c[5]||'').trim().toUpperCase();const yrs=Number((c.find((x,i)=>i>=6&&/^\d$/.test(x))||0));const money=c.filter(x=>/\$/.test(x)).map(cash);const value=money[0]||0,aav=money[1]||0,signingBonus=money[money.length-1]||0;out.push({year,round,pick,team:abbr,name,pos,years:yrs||4,totalValue:value,aav,signingBonus,fifthYearEligible:round===1,fifthYearOptionStatus:round===1?'Eligible after Year 3':'Not eligible',source:'Spotrac'});}return [...new Map(out.map(x=>[x.pick,x])).values()].sort((a,b)=>a.pick-b.pick)}
export function parseTeamYearOverview(html,teamAbbr,year){const all=rows(html),players=[];for(const c of all){if(c.length<6)continue;const name=(c[1]||'').trim(),pos=(c[2]||'').trim().toUpperCase();if(!name||/^player/i.test(name)||!pos||pos.length>6)continue;const money=c.filter(x=>/\$/.test(x)).map(cash);if(!money.length)continue;players.push({name,pos,capHit:money[0]||0,deadCap:money[1]||0,cash:money[2]||0,freeAgentYear:Number(c[c.length-1])||null});}return{team:teamAbbr,year,topContracts:players.sort((a,b)=>b.capHit-a.capHit).slice(0,12),source:'Spotrac'}}
export async function fetchHistoryYear(year){const y=Math.max(2022,Math.min(CURRENT,Number(year)||CURRENT));const [capHtml,posHtml]=await Promise.all([fetchText(`https://www.spotrac.com/nfl/cap/_/year/${y}`),fetchText(`https://www.spotrac.com/nfl/position/_/year/${y}`)]);return{year:y,caps:parseCapHistory(capHtml,y),positions:parsePositionHistory(posHtml,y),updatedAt:new Date().toISOString(),sourceUrls:[`https://www.spotrac.com/nfl/cap/_/year/${y}`,`https://www.spotrac.com/nfl/position/_/year/${y}`]}}
export async function fetchDraftYear(year=CURRENT){const y=Math.max(2022,Math.min(CURRENT,Number(year)||CURRENT));const urls=[`https://www.spotrac.com/nfl/draft/_/year/${y}`,`https://www.spotrac.com/nfl/draft/contracts/_/year/${y}`];let best=[],used='';for(const url of urls){try{const parsed=parseDraft(await fetchText(url),y);if(parsed.length>best.length){best=parsed;used=url;}if(parsed.length>=200)break;}catch{}}if(!best.length)throw new Error(`Spotrac draft tracker returned no rows for ${y}`);return{year:y,players:best,updatedAt:new Date().toISOString(),sourceUrl:used}}
export async function fetchTeamYearOverview(teamAbbr,year){const abbr=String(teamAbbr||'').toUpperCase(),slug=TEAM_SLUGS[abbr],y=Math.max(2022,Math.min(CURRENT,Number(year)||CURRENT));if(!slug)throw new Error('Unknown team');const url=`https://www.spotrac.com/nfl/${slug}/overview/_/year/${y}`;return{...parseTeamYearOverview(await fetchText(url),abbr,y),sourceUrl:url,updatedAt:new Date().toISOString()}}
