const TEAM_NAMES={Cardinals:'ARI',Falcons:'ATL',Ravens:'BAL',Bills:'BUF',Panthers:'CAR',Bears:'CHI',Bengals:'CIN',Browns:'CLE',Cowboys:'DAL',Broncos:'DEN',Lions:'DET',Packers:'GB',Texans:'HOU',Colts:'IND',Jaguars:'JAX',Chiefs:'KC',Raiders:'LV',Chargers:'LAC',Rams:'LAR',Dolphins:'MIA',Vikings:'MIN',Patriots:'NE',Saints:'NO',Giants:'NYG',Jets:'NYJ',Eagles:'PHI',Steelers:'PIT',Seahawks:'SEA','49ers':'SF',Buccaneers:'TB',Titans:'TEN',Commanders:'WAS'};
function clean(s){return String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&#39;|&apos;/gi,"'").replace(/&quot;/gi,'"').replace(/&ndash;|&#8211;/gi,'-').replace(/\s+/g,' ').trim()}
function norm(s){return String(s||'').toLowerCase().replace(/\b(jr|sr|ii|iii|iv)\.?\b/g,'').replace(/[^a-z0-9]/g,'')}
function cash(s){const m=String(s||'').replace(/,/g,'').match(/\$\s*([0-9]+(?:\.[0-9]+)?)/);return m?Math.round(Number(m[1])):0}
function amount(s){const m=String(s||'').replace(/,/g,'').match(/\$\s*([0-9]+(?:\.[0-9]+)?)\s*(million|m|thousand|k)?/i);if(!m)return 0;const mult=/million|m/i.test(m[2]||'')?1e6:/thousand|k/i.test(m[2]||'')?1e3:1;return Math.round(Number(m[1])*mult)}
function pct(s){const m=String(s||'').match(/([0-9]+(?:\.[0-9]+)?)\s*%/);return m?Number(m[1]):null}
function cells(row){const out=[];const re=/<t[dh]\b[^>]*>([\s\S]*?)<\/t[dh]>/gi;let m;while((m=re.exec(row)))out.push(clean(m[1]));return out}
function hrefFromFirstCell(row){const m=row.match(/<t[dh]\b[^>]*>[\s\S]*?<a\b[^>]*href=["']([^"']+)["']/i);if(!m)return'';return m[1].startsWith('http')?m[1]:`https://overthecap.com${m[1]}`}
export function parseOtcContracts(html){const rows=[];const tr=/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi;let m;while((m=tr.exec(html))){const c=cells(m[1]);if(c.length<7)continue;const name=c[0],position=c[1],team=TEAM_NAMES[c[2]]||'';if(!team||!name||/^player$/i.test(name))continue;const totalValue=cash(c[3]),apy=cash(c[4]),totalGuaranteed=cash(c[5]),avgGuaranteePerYear=cash(c[6]),guaranteePercent=pct(c[7]||'');if(!totalValue&&!apy&&!totalGuaranteed)continue;rows.push({name,position,team,totalValue,apy,totalGuaranteed,avgGuaranteePerYear,guaranteePercent,otcUrl:hrefFromFirstCell(m[1])});}return rows;}
async function fetchHtml(url,ms=18000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,headers:{'user-agent':'Mozilla/5.0 NFL-Cap-Tracker/7.2','accept':'text/html,application/xhtml+xml'}});if(!r.ok)throw new Error(`OTC HTTP ${r.status}`);return await r.text()}finally{clearTimeout(t)}}
function previousMoneyCell(c,start){for(let i=start;i>=0;i--){if(/\$/.test(c[i]||''))return{index:i,value:cash(c[i])}}return null}
export function parseOtcPlayerDetails(html){
 const text=clean(html),out={yearly:[]};
 let m=text.match(/Free Agency:\s*(\d{4})\s*\(([^)]+)\)/i);if(m){out.freeAgentYear=Number(m[1]);out.freeAgentStatus=m[2].trim().toUpperCase();out.contractEnd=out.freeAgentYear-1;}
 m=text.match(/Current Contract\s*\(([^,()]+),\s*signed\s*(\d{4})\)/i);if(m){out.contractType=m[1].trim();out.signedYear=Number(m[2]);}
 m=text.match(/signed (?:a|an)\s+(\d+)\s+year\s+(?:contract\s+)?(?:extension|contract)/i)||text.match(/Contract Terms:\s*(\d+)\s*yr/i);if(m)out.contractYears=Number(m[1]);
 m=text.match(/including\s+(\$[0-9.,]+\s*(?:million|m|thousand|k)?)\s+signing bonus/i);if(m)out.signingBonus=amount(m[1]);
 m=text.match(/with\s+(\$[0-9.,]+\s*(?:million|m|thousand|k)?)\s+(?:fully\s+)?guaranteed at signing/i);if(m)out.guaranteedAtSigning=amount(m[1]);
 if(!out.guaranteedAtSigning){m=text.match(/GTD at Sign:\s*(\$[0-9.,]+)/i);if(m)out.guaranteedAtSigning=amount(m[1]);}
 if(!out.signingBonus){m=text.match(/Signing Bonus:\s*(\$[0-9.,]+)/i);if(m)out.signingBonus=amount(m[1]);}
 if(out.contractEnd)out.yearsLeft=Math.max(0,out.contractEnd-2026+1);
 const lower=html.toLowerCase(),a=lower.indexOf('current contract'),b=lower.indexOf('contract notes',a+1),section=a>=0?html.slice(a,b>a?b:undefined):html;
 const tr=/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi;while((m=tr.exec(section))){const c=cells(m[1]);const ym=String(c[0]||'').match(/^(20\d{2})\b/);if(!ym)continue;const year=Number(ym[1]);const percentIndex=c.findIndex((v,i)=>i>1&&/%/.test(v||''));const capCell=previousMoneyCell(c,(percentIndex>0?percentIndex:c.length)-1);if(!capCell)continue;const guaranteedCell=previousMoneyCell(c,capCell.index-1);const dollars=[];for(let i=2;i<capCell.index;i++)if(/\$/.test(c[i]||''))dollars.push(cash(c[i]));const baseSalary=dollars[0]||0,bonusProration=dollars[1]||0;const bonusMiddle=dollars.slice(2,Math.max(2,dollars.length-(guaranteedCell?1:0)));const rosterOtherBonus=bonusMiddle.reduce((s,n)=>s+n,0);out.yearly.push({year,baseSalary,bonusProration,rosterOtherBonus,guaranteedSalary:guaranteedCell?.value||0,capHit:capCell.value});}
 if(out.yearly.length){const y2026=out.yearly.find(y=>y.year===2026);if(y2026){out.bonusProration2026=y2026.bonusProration;out.rosterOtherBonus2026=y2026.rosterOtherBonus;if(y2026.guaranteedSalary)out.guaranteed2026=y2026.guaranteedSalary;}}
 return out;
}
export async function enrichOtcPlayer(player){if(!player?.otcUrl)throw new Error('No Over The Cap player URL available');const html=await fetchHtml(player.otcUrl,15000);const details=parseOtcPlayerDetails(html);if(!details.signedYear&&!details.contractEnd&&!details.yearly.length)throw new Error('OTC player detail parser found no contract structure');Object.assign(player,details);player.sourceChecks={...(player.sourceChecks||{}),OTC:true};player.contractSource=[player.contractSource,'OverTheCap'].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i).join(' + ');player.contractUpdatedAt=new Date().toISOString();return player;}
export async function syncOtcContracts(state){const url='https://overthecap.com/contracts',html=await fetchHtml(url),rows=parseOtcContracts(html);if(rows.length<400)throw new Error(`OTC contract parser found only ${rows.length} players`);const now=new Date().toISOString();let matched=0;for(const c of rows){const p=state.players.find(x=>x.status!=='removed'&&x.team===c.team&&norm(x.name)===norm(c.name));if(!p)continue;p.totalValue=c.totalValue||p.totalValue||0;p.apy=c.apy||p.apy||0;p.totalGuaranteed=c.totalGuaranteed||p.totalGuaranteed||0;p.avgGuaranteePerYear=c.avgGuaranteePerYear||p.avgGuaranteePerYear||0;if(c.guaranteePercent!==null)p.guaranteePercent=c.guaranteePercent;p.otcUrl=c.otcUrl||p.otcUrl;p.sourceChecks={...(p.sourceChecks||{}),OTC:true};p.contractSource=[p.contractSource,'OverTheCap'].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i).join(' + ');p.contractUpdatedAt=now;matched++;}state.lastOtcSync=now;return{source:'OverTheCap contracts',players:rows.length,matched,url};}
