const TEAM_SLUGS={
 ARI:'arizona-cardinals',ATL:'atlanta-falcons',BAL:'baltimore-ravens',BUF:'buffalo-bills',CAR:'carolina-panthers',CHI:'chicago-bears',CIN:'cincinnati-bengals',CLE:'cleveland-browns',DAL:'dallas-cowboys',DEN:'denver-broncos',DET:'detroit-lions',GB:'green-bay-packers',HOU:'houston-texans',IND:'indianapolis-colts',JAX:'jacksonville-jaguars',KC:'kansas-city-chiefs',LV:'las-vegas-raiders',LAC:'los-angeles-chargers',LAR:'los-angeles-rams',MIA:'miami-dolphins',MIN:'minnesota-vikings',NE:'new-england-patriots',NO:'new-orleans-saints',NYG:'new-york-giants',NYJ:'new-york-jets',PHI:'philadelphia-eagles',PIT:'pittsburgh-steelers',SF:'san-francisco-49ers',SEA:'seattle-seahawks',TB:'tampa-bay-buccaneers',TEN:'tennessee-titans',WAS:'washington-commanders'
};
function cleanText(html){return String(html||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&#39;|&apos;/gi,"'").replace(/&quot;/gi,'"').replace(/&ndash;|&#8211;/gi,'-').replace(/\s+/g,' ').trim()}
function norm(s){return String(s||'').toLowerCase().replace(/\b(jr|sr|ii|iii|iv)\.?\b/g,'').replace(/[^a-z0-9]/g,'')}
function cash(s){const m=String(s||'').replace(/,/g,'').match(/\$\s*([0-9]+(?:\.[0-9]+)?)/);return m?Math.round(Number(m[1])):0}
function integer(s){const m=String(s||'').match(/^\s*(\d{1,4})\s*$/);return m?Number(m[1]):null}
function cellsFromRow(rowHtml){const out=[];const re=/<t[dh]\b[^>]*>([\s\S]*?)<\/t[dh]>/gi;let m;while((m=re.exec(rowHtml)))out.push(cleanText(m[1]));return out}
function pos(v){const p=String(v||'').trim().toUpperCase();return p==='ED'?'EDGE':p}
export function parseSpotracContracts(html){const rows=[],seen=new Set(),trRe=/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi;let tr;while((tr=trRe.exec(html))){const c=cellsFromRow(tr[1]);if(c.length<8)continue;const name=(c[0]||'').trim(),position=pos(c[1]);if(!name||/^player/i.test(name)||!position||position.length>8)continue;let signedYear=null,contractEnd=null,contractYears=null,totalValue=0,apy=0,guaranteedAtSigning=0,practicalGuarantee=0,contractType='';if(c.length>=12&&(/\$/.test(c[8]||'')||/\$/.test(c[9]||''))){signedYear=integer(c[5])||integer(c[2]);contractEnd=integer(c[6]);contractYears=integer(c[7]);contractType=c[3]||'';totalValue=cash(c[8]);apy=cash(c[9]);guaranteedAtSigning=cash(c[10]);practicalGuarantee=cash(c[11]);}else{const moneyCells=c.map((v,i)=>({v,i,n:cash(v)})).filter(x=>/\$/.test(x.v));if(moneyCells.length<2)continue;const nums=c.map(v=>integer(v)).filter(x=>x!==null),years=nums.filter(x=>x>=2000&&x<=2100),short=nums.filter(x=>x>=1&&x<=10);signedYear=years[0]||null;contractEnd=years[years.length-1]||null;contractYears=short[short.length-1]||null;totalValue=moneyCells[0]?.n||0;apy=moneyCells[1]?.n||0;guaranteedAtSigning=moneyCells[2]?.n||0;practicalGuarantee=moneyCells[3]?.n||guaranteedAtSigning;}if(!totalValue&&!apy&&!practicalGuarantee&&!guaranteedAtSigning)continue;const key=norm(name);if(!key||seen.has(key))continue;seen.add(key);rows.push({name,position,totalValue,apy,guaranteedAtSigning,totalGuaranteed:practicalGuarantee||guaranteedAtSigning,signedYear,contractEnd,contractYears,contractType});}return rows;}
async function fetchWithTimeout(url,ms=20000){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{signal:c.signal,headers:{'user-agent':'Mozilla/5.0 NFL-Cap-Tracker/7.0','accept':'text/html,application/xhtml+xml'}})}finally{clearTimeout(t)}}
export async function fetchSpotracTeam(abbr){const slug=TEAM_SLUGS[abbr];if(!slug)throw new Error(`No Spotrac slug for ${abbr}`);const urls=[`https://www.spotrac.com/nfl/${slug}/contracts/1000`,`https://www.spotrac.com/nfl/${slug}/contracts`];let last='';for(const url of urls){try{const r=await fetchWithTimeout(url);if(!r.ok){last=`HTTP ${r.status}`;continue}const rows=parseSpotracContracts(await r.text());if(rows.length>=15)return{url,rows};last=`parser ${rows.length}`;}catch(e){last=String(e.message||e)}}throw new Error(`Spotrac ${abbr} failed: ${last}`)}
function mergeTeam(state,abbr,data,now){let matched=0,added=0;const teamPlayers=state.players.filter(p=>p.team===abbr&&p.status!=='removed');for(const c of data.rows){let p=teamPlayers.find(x=>norm(x.name)===norm(c.name));if(!p){p={team:abbr,name:c.name,position:c.position,status:'active',source:'Spotrac contract sync'};state.players.push(p);teamPlayers.push(p);added++;}p.position=p.position||c.position;p.totalValue=c.totalValue||p.totalValue||0;p.apy=c.apy||p.apy||0;p.totalGuaranteed=c.totalGuaranteed||p.totalGuaranteed||0;p.guaranteedAtSigning=c.guaranteedAtSigning||p.guaranteedAtSigning||0;p.signedYear=c.signedYear||p.signedYear;p.contractEnd=c.contractEnd||p.contractEnd;p.contractYears=c.contractYears||p.contractYears;p.contractType=c.contractType||p.contractType||'';if(c.contractEnd)p.yearsLeft=Math.max(0,c.contractEnd-2026+1);p.contractStatus='verified';p.contractSource=[p.contractSource,'Spotrac'].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i).join(' + ');p.contractUpdatedAt=now;p.spotracSourceUrl=data.url;p.sourceChecks={...(p.sourceChecks||{}),Spotrac:true};matched++;}const t=state.teams.find(x=>x.abbr===abbr);if(t){t.contractsUpdatedAt=now;t.spotracContractCount=data.rows.length;}return{abbr,matched,added,players:data.rows.length,url:data.url}}
async function mapLimit(items,limit,fn){let i=0;const out=[];async function worker(){while(i<items.length){const idx=i++;try{out[idx]=await fn(items[idx],idx)}catch(e){out[idx]={abbr:items[idx]?.abbr,error:String(e.message||e)}}}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return out}
export async function syncSpotracLeague(state){const now=new Date().toISOString();const results=await mapLimit(state.teams,4,async t=>mergeTeam(state,t.abbr,await fetchSpotracTeam(t.abbr),now));const ok=results.filter(r=>!r.error),failed=results.filter(r=>r.error);state.lastSpotracSync=now;state.syncLog=state.syncLog||[];state.syncLog.unshift({timestamp:now,status:ok.length>=30?'ok':'partial',message:`Spotrac contract sync: ${ok.length}/32 teams, ${ok.reduce((n,r)=>n+(r.players||0),0)} contracts.${failed.length?' Failed: '+failed.map(x=>x.abbr).join(', '):''}`});state.syncLog=state.syncLog.slice(0,300);return{source:'Spotrac',teams:ok.length,players:ok.reduce((n,r)=>n+(r.players||0),0),results,failures:failed}}
